In [4]:
names = open('names.txt',  'r').read().splitlines()

In [82]:
#ahora que tegno todas los nombres con las repeticiones de 2 letras seguidas, para todas las letras
# lo que quiero hacer es ordenar este diccionarion donde la tupla mas repetidas este primero en orden desendienete
# luego con eso voy a poder tomar la probabilidad de que cada tupla exita, y la voy a normalizar para que la suma de todas la probablidades de las tuplas me de 1.

In [83]:

b_sorted = sorted(b.items(), key=lambda x: -x[1]) # b.items() hace una lista de tuplas del tipo (tupla,valor), luego por default, sorted esta en el primer elemento, así que necesitamos cambiarlo para que tome como referencia el segundo elemento
# key=lambda x(puede ser cualquier otro nombre): -x[1]

In [1]:
# es mucho mas conveniente usar arrays antes que el diccionario de python
import torch

In [2]:
N = torch.zeros((27, 27) , dtype = torch.int32)


In [26]:
 # hago un diccionarion con las dos letras y las veces que aparecen
for name in names:
    chs = ['.'] + list(name) + ['.'] # le agrego a cada nombre un simbolo de Start y de Ending
    for ch1, ch2 in zip (chs, chs[1:]): # esta es una bonita forma de ir ordenando en al nombre y al nombre sin su primera letra
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [25]:
chars = sorted(list(set(''.join(names))))
stoi = {s:i+1 for i, s in enumerate(chars)} # esto hace que cada elemento de chars se le asigne un numero, hasta la cantidad de elementos de chars
# ''.join(names) junta todos los nombres en una sola string
# set lo que hace es hacer un conjunto, el cual no tiene repetidos
# stoi, es una forma de crear un diccionario. enumerate(chars) crea una lista de tuplas asignandole un numero a cada elemento de chars, si chars = ['a','b','c'] entonces enumerate(chars) = [('a',0, ('b,1), ('c',2))]  
stoi['.'] =0
itos = {i:s for s, i in stoi.items()}

In [24]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [21]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [27]:
p = N[0].float()
p = p/p.sum()
# ahora teniendo esto, osea, las probabilidades, vamos a usar torch.multinomial, al cual le das probabilidades y te devuelve muestras.
# tambien vamos a usar un generator, para que nos de los mismos ejemplos que en el video


In [28]:

g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
ix

10

In [29]:
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [30]:
torch.multinomial(p, num_samples =20, replacement= True, generator = g)

tensor([19, 18, 14, 20,  5,  3, 20, 15, 20, 11, 10, 10, 14, 19, 12,  5, 13, 14,
         1, 11])

In [1]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p num_samples= 1, replacement= True, generator =g).item() # se usa al final el .item() porque te sino te devuelve un valor .torch, son item() podemos obtener el valor.
itos[ix] # itos a partir de un numero te da una letra, entonces ix, necesita ser un valor int.


SyntaxError: invalid syntax (2679451798.py, line 2)

In [ ]:
g = torch.Generator().manual_seed(2147483647)
for i in range(20):
    ix = 0
    word = []
    while True:
        p = N[ix].float()
        p = p / p.sum()
        ix = torch.multinomial(p, num_samples=1, replacement= True, generator = g).item()
        word.append(itos[ix])
        if ix == 0:
            break
    print(''.join(word))
# el problema con este es que no conoce lo que paso antes de la letra, por ejemplo 'a.' pasó esto  porque a es muy probalble de terminar, pero no sabe que antes no había nada